Added missing check for subscription creation
Also added some methods for knowing about the error.

Fixes: 
Fatal error: Call to undefined method WP_Error::add_product() in /var/www/anotherscan2cad/staging-site/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscriptions-manager.php on line 473